application/urls.py
from django.urls import path, include
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.newIndexView, name='index'),
    path('article/<int:article_id>/', views.newDetailView, name='detail'),
    path('movies/', views.movieFeed, name='moviefeed'),
    path('games/', views.gameFeed, name='gamefeed'),
    path('gadgets/', views.gadgetFeed, name='gadgetfeed'),
    path('videos/', views.videoFeed, name='videofeed'),
    path('video/<int:video_id>/', views.videoDetail, name='detailvideo'),
    path('register/', views.register, name='signup'),

]

retroreview/urls.py
from django.contrib import admin
from django.urls import include, path
from application import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('retro/', include(urls)),
    path('admin/', admin.site.urls),
    path('retro/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('retro/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('retro/password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('retro/password-change-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('retro/password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('retro/password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('retro/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('retro/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

application/models.py
from django.db import models
from django.utils import timezone
import datetime
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser
from taggit.managers import TaggableManager
from django.conf import settings
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.



class CustomUser(AbstractUser):
    mobile_number = models.CharField(max_length=10)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.username

class Article(models.Model):
    title_text = models.CharField(max_length=100, null=True)
    article_text = models.CharField(max_length=2000)
    pub_date = models.DateTimeField('date published')
    header_image = models.ImageField(upload_to='images/', null=True)
    article_body_text = RichTextField()
    article_author = models.CharField(max_length=100, null=True)
    tags = TaggableManager()

    def __str__(self):
        return self.title_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Comment(MPTTModel):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    active = models.BooleanField(default=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments', null=True)
    parent = TreeForeignKey('self', related_name='children', null=True, on_delete=models.CASCADE, db_index=True)

    class MPTTMeta:
        order_insertion_by = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.id, self.created_by)


    def save_model(self, request, obj, form, change):
        if not obj.pk:
            obj.created_by = request.user
        super().save_model(request, obj, form, change)


class UpVotes(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    vote_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.vote_text

class VideoLink(models.Model):
    video_title = models.CharField(max_length=100, null=True)
    video_url = models.CharField(max_length=100, null=True)
    pub_date = models.DateTimeField('date published', null=True)

application/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Comment
from django.forms import ModelForm, Textarea
import logging


logger = logging.getLogger("mylogger")

class CustomUserCreationForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'mobile_number' )

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'mobile_number' )

class CommentForm(ModelForm):
    text = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':3, 'cols':115, 'style':'width: 90%; resize:none;'}))
    parent_id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    
    def clean_parent_id(self):
        parent_id = self.cleaned_data['parent_id']
        logger.info("-------------------------------")
        logger.info("Logging parent id from forms:")
        logger.info(parent_id)
        logger.info("-------------------------------")

    class Meta:
        model = Comment
        fields= ('text',)

application/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.views import generic
from .models import Article, VideoLink, Comment
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.template import RequestContext
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from .forms import CustomUserCreationForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import logging


logger = logging.getLogger("mylogger")

class IndexView(generic.ListView):
    template_name = 'application/index.html'
    context_object_name = 'latest_article_list'

    def get_queryset(self):
        return Article.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Article
    template_name = 'application/detail.html'




def newIndexView(request):
    latest_article_list = Article.objects.order_by('-pub_date')[:5]
    latest_top_article = Article.objects.filter(tags__name__in=["Top Stories"]).order_by('-pub_date')[0]
    second_latest_top_article = Article.objects.filter(tags__name__in=["Top Stories"]).order_by('-pub_date')[1]
    third_latest_top_article = Article.objects.filter(tags__name__in=["Top Stories"]).order_by('-pub_date')[2]
    fourth_latest_top_article = Article.objects.filter(tags__name__in=["Top Stories"]).order_by('-pub_date')[3]
    latest_video_list = VideoLink.objects.order_by('-pub_date')[:5]
    return render(request, 'application/index.html', {'latest_article_list': latest_article_list, 'latest_top_article': latest_top_article, 'second_latest_top_article': second_latest_top_article, 'third_latest_top_article': third_latest_top_article, 'fourth_latest_top_article': fourth_latest_top_article, \
    'latest_video_list': latest_video_list })

def movieFeed(request):
    latest_movie_list = Article.objects.filter(tags__name__in=["Movies"]).order_by('-pub_date')[:10]
    return render(request, 'application/movie-feed.html', {'latest_movie_list': latest_movie_list})

def gameFeed(request):
    latest_game_list = Article.objects.filter(tags__name__in=["Games"]).order_by('-pub_date')[:10]
    return render(request, 'application/game-feed.html', {'latest_game_list': latest_game_list})

def gadgetFeed(request):
    latest_gadget_list = Article.objects.filter(tags__name__in=["Gadgets"]).order_by('-pub_date')[:10]
    return render(request, 'application/gadget-feed.html', {'latest_gadget_list': latest_gadget_list})

def newDetailView(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    page = request.GET.get('page', 1)
    comments = article.comments.filter(active=True)
    comment = None
    username = None
    parent_id = None
    if request.user.is_authenticated:
        username = request.user.username;
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            parent_id = comment_form['parent_id'].value()
            logger.info("-------------------------------")
            logger.info("Logging parent id:")
            logger.info(parent_id)
            logger.info("-------------------------------")
            if parent_id is not None and parent_id != '':
                parent = Comment.objects.get(pk=parent_id)
                comment = comment_form.save(commit=False)
                comment.parent = parent;
                comment.article = article
                comment.created_by = request.user
                comment.save()
                return redirect('articles:detail', article_id=article.id)
            else:
                comment = comment_form.save(commit=False)
                comment.article = article
                comment.created_by = request.user
                comment.save()
                return redirect('articles:detail', article_id=article.id)
    else:
        comment_form = CommentForm()
    return render(request, 'application/detail.html', {'article': article, 'comments': comments, 'comment': comment, 'comment_form': comment_form, 'username': username})




def videoDetail(request, video_id):
    videoLink = get_object_or_404(VideoLink, pk=video_id)
    return render(request, 'application/video-detail.html', {'videoLink': videoLink})

def videoFeed(request):
    latest_video_list = VideoLink.objects.order_by('-pub_date')[:10]
    return render(request, 'application/video-feed.html', {'latest_video_list': latest_video_list})

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('articles:index'), RequestContext(request))
    registered = False
    if request.method == 'POST':
        user_form = CustomUserCreationForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            return render(request, 'registration/registration_complete.html')

    else:
        user_form = CustomUserCreationForm()
    return render(request,'registration/register.html',
                          {'form':user_form})

application/templates/application/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Retro Reviews</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'application/js/global.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'application/css/style.css' %}">
  <script>

  $(document).ready(function(){

      $(".replyclicker").click(function(){
        var form = $("#commentform").clone(true);
        var that = $(this).parent().parent().children()[0];
        console.log(that);
        var otherId = that.innerHTML;
        console.log(otherId)
        var parentId = parseInt(otherId);
        console.log(parentId)
        form.find('#id_parent_id').val(parentId);
        var cancelbtn=$('<input/>').attr({
        type: "button",
        id: "field",
        value: 'cancel',
        class: "btn btn-danger btn-lg",
        onclick: "destroyform(this)"
    });
      form.append(cancelbtn)
        $(this).parent().append(form);

        $(this).hide();     
            });
          });

  function destroyform(element) {
    console.log("Calling Destroy Form");
    var thiselement = $(element).parent();
    console.log(thiselement);
    var nextelement = $(element).parent().parent().children()[1];
    console.log(nextelement);
    thiselement.remove();
    $(nextelement).show();
  }
  </script>

</head>
<body>

</body>
{% include "navbar.html" %}
<div class="content-container">
{% block content %}

{% endblock %}
</div>
<div class="footer">
    <p>Forte Corp &copy;</p>
  </div>
</html>

application/templates/application/comment-detail.html
{% extends 'application/base.html' %}
{% load static %}
{% block content %}
<div class="detail-cont">
<div class="article-detail-cont">
<div class="detail-title-cont">
<h1 class="detail-title-cont">{{ article.title_text }}</h1>
</div>
<p>{{ comment.created_by }}</p>
<p>by {{ comment.created_on }}
<h3 class="detail-sub-text">{{ comment.text }}</h3>
</div>

<div id="commentBox" class="commentBox">
<h2>{{ reply_list.count }} Replies</h2>
<hr>
{% if not user.is_authenticated %}
<div>
<a href="{% url 'login' %}">Login to comment</a>
</div>
{% endif %}
  {% if reply_list %}
  {% for reply in reply_list %}
       <div class="comments" style="padding: 10px;">

         <p class="font-weight-bold">
           {{ reply.created_by }} <br>
           <span class=" text-muted font-weight-normal">
             {{ reply.created_on }}
           </span>
         </p>
        <div class="comment_header">
        {% if user.is_authenticated %}
         {% if reply.created_by == user %}
            <a href="#">Edit</a>
         {% endif %}
         {% endif %}
        </div>
         <div class="single_comment">
         {{ reply.text | linebreaks }}
         </div>
       </div>
       {% endfor %}
  {% else %}
      <p>No Replies Yet</p>
  {% endif %}

        {% if user.is_authenticated %}
<div>
        <form method="post" style="margin-top: 1.3em;">
          {{ reply_form.as_p }}
          {% csrf_token %}
          <button type="submit" onclick="postComment()" class="btn btn-primary  btn-lg">Submit</button>
        </form>
      </div>
        {% endif %}
          </div>
        </div>
</div>
{% endblock %}

application/templates/application/detail.html
{% extends 'application/base.html' %}
{% load static %}
{% load mptt_tags %}
{% block content %}
<div class="detail-cont">
<div class="article-detail-cont">
<div class="detail-title-cont">
<h1 class="detail-title-cont">{{ article.title_text }}</h1>
</div>
<p>{{ article.pub_date }}</p>
<p>by {{ article.article_author }}

<div class="detail-image-cont" >
<img class="detail-image" src="{{ article.header_image.url }}" alt="Card image cap">
<h3 class="detail-sub-text">{{ article.article_text }}</h3>
</div>
<div class="detail-body-text">
{{ article.article_body_text | safe }}
</div>
</div>

<div id="commentBox" class="commentBox">
<h2>{{ comments.count }} Comments</h2>
<hr>
{% if not user.is_authenticated %}
<div>
<a href="{% url 'login' %}">Login to comment</a>
{% else %}
  <div>
        <form id="commentform" method="post" style="margin-top: 1.3em; margin-left: 55px; margin-bottom: 20px;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
      </div>

{% endif %}
  {% if comments %}
  <div class="comments" style="padding: 10px;">
    {% recursetree comments %}
        <div class="comment-container">
          <p id="hiddenIDField{{ node.id }}" style="display: none;">{{ node.id  }}</p>
         <p class="font-weight-bold">
           {{ node.created_by }}
           <span class=" text-muted font-weight-normal">
             {{ node.created_on }}
           </span>
         
         </p>
        
         <div class="single_comment">
         {{ node.text | linebreaks }}
         </div>
         <span style="float:right;">    
          <a href="#">View All Replies({{ node.get_descendant_count }})</a>      
          {% if user.is_authenticated and node.created_by != user %}   
              <button class="replyclicker">Reply</button>
              {% endif %}
           {% if node.created_by == user %}
              <a href="#">Edit</a>
          
           {% endif %}</span>
       {% if not node.is_leaf_node %}
         {% if node.level < 2 %}
         <div class="reply-comment">
         {{ children }}
        </div>
          {% endif %}
          {% endif %}
         
        </div> 
        {% endrecursetree %}
       </div>

  {% else %}
      <p>No Comments Yet</p>
  {% endif %}

</div>
      </div>
          </div>
{% endblock %}

application/templates/application/gadget-feed.html
{% extends 'application/base.html' %}
{% load static %}
{% block content %}
<div class="container feed-container">
<div class="top-story-cont">
</div>
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8"><h1 class="header-title">Latest Gadget News and Reviews <span class="glyphicon glyphicon-fire text-danger"></span></h1></div>
    <div class="col-lg-2"></div>

</div>
<div class="latest-news-container">
  <div class="row ">
      <div class="col-lg-3">
      </div>
      <div class="col-lg-6">
{% if latest_gadget_list %}

    {% for article in latest_gadget_list %}


        <div class="row">
            <div class="col-xs-2"></div>
            <div class="col-xs-8"><a href="{% url 'articles:detail' article.id %}"><img class="card-img-top article-image" src="{{ article.header_image.url }}" alt="Card image cap"></a>
                <div class="card-body">
                    <h3 class="card-title"><a href="{% url 'articles:detail' article.id %}">{{ article.title_text }} </a></h3>
                    <p>{{ article.pub_date }}</p>
                    <h4 class="card-text">{{ article.article_text }}</h4>
                    <a href="{% url 'articles:detail' article.id %}" class="btn btn-primary btn-lg read-btn">Read More</a>
                  </div>
            </div>
            <div class="col-xs-2"></div>
        </div>
      <hr>


    {% endfor %}
{% else %}
    <p>No articles are available.</p>
{% endif %}
</div>
<div class="col-lg-3"></div>
</div>
</div>
</div>
{% endblock %}

application/templates/application/game-feed.html
{% extends 'application/base.html' %}
{% load static %}
{% block content %}
<div class="container feed-container">
<div class="top-story-cont">
</div>
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8"><h1 class="header-title">Latest Game News and Reviews <span class="glyphicon glyphicon-fire text-danger"></span></h1></div>
    <div class="col-lg-2"></div>

</div>
<div class="latest-news-container">
  <div class="row ">
      <div class="col-lg-3">
      </div>
      <div class="col-lg-6">
{% if latest_game_list %}

    {% for article in latest_game_list %}


        <div class="row">
            <div class="col-xs-2"></div>
            <div class="col-xs-8"><a href="{% url 'articles:detail' article.id %}"><img class="card-img-top article-image" src="{{ article.header_image.url }}" alt="Card image cap"></a>
                <div class="card-body">
                    <h3 class="card-title"><a href="{% url 'articles:detail' article.id %}">{{ article.title_text }} </a></h3>
                    <p>{{ article.pub_date }}</p>
                    <h4 class="card-text">{{ article.article_text }}</h4>
                    <a href="{% url 'articles:detail' article.id %}" class="btn btn-primary btn-lg read-btn">Read More</a>
                  </div>
            </div>
            <div class="col-xs-2"></div>
        </div>
      <hr>


    {% endfor %}
{% else %}
    <p>No articles are available.</p>
{% endif %}
</div>
<div class="col-lg-3"></div>
</div>
</div>
</div>
{% endblock %}

application/templates/application/index.html
{% extends 'application/base.html' %}
{% load static %}
{% block content %}
<div class="container feed-container">
<div class="top-story-cont">
<div class="row">
    <div class="col-lg-3">
            <a href="{% url 'articles:detail' third_latest_top_article.id %}">
            <div class="top-story-single">
            <img class="top-article-image" src="{{ third_latest_top_article.header_image.url }}" alt="Card image cap">
            <div class="overlay"></div>

            <div class="top-article-image-overlay"><h3>{{ third_latest_top_article.title_text }}</h3></div>
            </div>
            </a>

    </div>
    <div class="col-lg-3">
        <div class="zoom">
            <a href="{% url 'articles:detail' latest_top_article.id %}">
            <div class="top-story-single">
            <img class="top-article-image" src="{{ latest_top_article.header_image.url }}" alt="Card image cap">
            <div class="overlay"></div>
            <div class="top-article-image-overlay"><h3>{{ latest_top_article.title_text }}</h3></div>
            </div>
            </a>
          </div>
    </div>


    <div class="col-lg-3">
        <div class="zoom">
          <a href="{% url 'articles:detail' second_latest_top_article.id %}">
            <div class="top-story-single">
          <img class="top-article-image" src="{{ second_latest_top_article.header_image.url }}" alt="Card image cap">
          <div class="overlay"></div>
          <div class="top-article-image-overlay"><h3>{{ second_latest_top_article.title_text }}</h3></div>
        </div>
          </a>
        </div>
</div>
<div class="col-lg-3">
    <div class="zoom">
        <a href="{% url 'articles:detail' fourth_latest_top_article.id %}">
        <div class="top-story-single">
        <img class="top-article-image" src="{{ fourth_latest_top_article.header_image.url }}" alt="Card image cap">
        <div class="overlay"></div>
        <div class="top-article-image-overlay"><h3>{{ fourth_latest_top_article.title_text }}</h3></div>
        </div>
        </a>
      </div>
</div>
</div>
</div>
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8"><h1 class="header-title">Latest Articles and News <span class="glyphicon glyphicon-fire text-danger"></span></h1></div>
    <div class="col-lg-2"></div>

</div>
<div class="latest-news-container">
  <div class="row ">
      <div class="col-lg-3">
        <h2>Videos</h2>
        {% if latest_video_list %}
        {% for video in latest_video_list %}
        <div class="video-box">
        <iframe width="420" height="345" src="{{ video.video_url }}">
        </iframe>
        <a href="{% url 'articles:detailvideo' video.id %}" class="btn btn-danger btn-lg read-btn">Watch More</a>
        </div>
        <br>
        {% endfor %}
    {% else %}
        <p>No videos are available.</p>
    {% endif %}


      </div>
      <div class="col-lg-6">
{% if latest_article_list %}

    {% for article in latest_article_list %}


        <div class="row">
            <div class="col-xs-2"></div>
            <div class="col-xs-8"><a href="{% url 'articles:detail' article.id %}"><img class="card-img-top article-image" src="{{ article.header_image.url }}" alt="Card image cap"></a>
                <div class="card-body">
                    <h3 class="card-title"><a href="{% url 'articles:detail' article.id %}">{{ article.title_text }} </a></h3>
                    <p>{{ article.pub_date }}</p>
                    <h4 class="card-text">{{ article.article_text }}</h4>
                    <a href="{% url 'articles:detail' article.id %}" class="btn btn-primary btn-lg read-btn">Read More</a>
                  </div>
            </div>
            <div class="col-xs-2"></div>
        </div>
      <hr>


    {% endfor %}
{% else %}
    <p>No articles are available.</p>
{% endif %}
</div>
<div class="col-lg-3"><a class="twitter-timeline" href="https://twitter.com/RetReview?ref_src=twsrc%5Etfw">Tweets by RetReview</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> </div>
</div>
</div>
</div>
{% endblock %}

application/templates/application/movie-feed.html
{% extends 'application/base.html' %}
{% load static %}
{% block content %}

{% endblock %}

application/templates/application/video-detail.html
{% extends 'application/base.html' %}
{% load static %}
{% block content %}
<div class="detail-cont">
<div class="article-detail-cont">
<div class="detail-title-cont">
<h1 class="detail-title-cont">{{ videoLink.video_title }}</h1>
</div>
<p>{{ videoLink.pub_date }}</p>

<div >
  <div class="video-frame-cont">
  <iframe src="{{ videoLink.video_url }}" allowfullscreen>
  </iframe>
  </div>
</div>
<div class="detail-body-text">

</div>
</div>
</div>
{% endblock %}

application/templates/application/video-feed.html
{% extends 'application/base.html' %}
{% load static %}
{% block content %}
<div class="container feed-container">
<div class="top-story-cont">
</div>
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8"><h1 class="header-title">Latest Video News and Reviews <span class="glyphicon glyphicon-fire text-danger"></span></h1></div>
    <div class="col-lg-2"></div>

</div>
<div class="latest-news-container">
  <div class="row ">
      <div class="col-lg-3">
      </div>
      <div class="col-lg-6">
{% if latest_video_list %}

    {% for videoLink in latest_video_list %}

                  <div class="article-detail-cont">
                  <div class="detail-title-cont">
                  <h1 class="detail-title-cont">{{ videoLink.video_title }}</h1>
                  </div>
                  <p>{{ videoLink.pub_date }}</p>

                  <div >
                    <div class="video-frame-cont">
                    <iframe src="{{ videoLink.video_url }}" allowfullscreen>
                    </iframe>
                    </div>
                  </div>
                  <div class="detail-body-text">

                  </div>
                  </div>


      <hr>


    {% endfor %}
{% else %}
    <p>No videos are available.</p>
{% endif %}
</div>
<div class="col-lg-3"></div>
</div>
</div>
</div>
{% endblock %}